### ISSUE TITLE
Question: React component library

### ISSUE THREAD

**Issue by bclark-p44** [milesj/packemon#126]
Howdy Miles,

I am building a design system and using packemon for my bundler. I have a package that contains all of my react components, and I'm wondering about the recommended setup for optimal tree-shaking for such a package. By default, packemon supports tree-shaking by utilizing pure annotations, which gets me most of the way there.  

One goal I would like to accomplish is individual component imports:

```
import Component from '@package/react/Component`;
```

After reading through the documentation the two solutions I've identified are:

1. Create an input for each component.
2. Override the default Rollup config to add inputs for each component.

I just want to make sure I'm going down the right path and there isn't something glaringly obvious I'm missing.

Thanks in advance!

**Comment by milesj** [comment]
@bclark-p44 You probably want to set `bundle: false` in the config: https://packemon.dev/docs/config#bundle

This will output files in a 1:1 matching structure to the original source folder, and avoids you having to put an input for every component. Consumers can then just deep import matching the file structure.

**Comment by bclark-p44** [comment]
Thanks! I will give that a shot
