### ISSUE TITLE
`const __dirname`  throw "Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "CallExpression""

### ISSUE THREAD

**Issue by azu** [milesj/packemon#137]
packemon throw an error when transpile following code.

> Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "CallExpression"

```js
const __dirname = 1;
```

This this a parts of following snippet.

```js
import * as path from "path";
import * as url from "url";

const __filename__ = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename__);
console.log(__dirname);
```

I know that [babel-plugin-cjs-esm-interop](https://www.npmjs.com/package/babel-plugin-cjs-esm-interop) transpile `__dirname`.
But, This error is unexpected.

## Expected

No Error

## Actual

Error:

> Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "CallExpression""

## Workaround

Avoid to define `__dirname` variable.

```js
import * as path from "path";
import * as url from "url";

const x = url.fileURLToPath(import.meta.url);
const y = path.dirname(x);
console.log(y);
```

## Reproduce Repository

https://github.com/azu/packemon-mjs-__dirname-error

**Comment by milesj** [comment]
Thanks, will be resolved by https://github.com/milesj/packemon/commit/05722cc1a5415a636b7e91f39ec187f4b42f9448

**Comment by milesj** [comment]
Released!
