### ISSUE TITLE
`packemon build` doc is outdated?

### ISSUE THREAD

**Issue by azu** [milesj/packemon#147]
packemon v2 removed multiple formats option.
https://packemon.dev/docs/migrate/2.0#removed-multiple-format-support-when-configuring-a-package
https://github.com/milesj/packemon/pull/119

However, `packemon build` docs has referred multiple `formats` option.

> "formats": ["lib", "esm", "umd"],
https://packemon.dev/docs/build#how-it-works

Actually, This example configuration looks like invalid.

- Reproduce: https://github.com/azu/packemon-build-formats

```
❯ npm run build

> packemon-build-formats@1.0.0 build
> packemon build


 ERROR

 The following validations have failed for `packemon-build-formats`:
   - Unknown fields: formats.
```

**Comment by milesj** [comment]
The docs were wrong, just fixed, thanks.
