### ISSUE TITLE
Unable to use `PackageValidator` for non-packemon packages

### ISSUE THREAD

**Issue by j3tan** [milesj/packemon#177]
Version: `3.x`

The [requirement for a `Package` to have a packemon configuration object](https://github.com/milesj/packemon/blob/c40d20d06217d9cd6fc0e8fc67b52652a4707b25/packages/packemon/src/Package.ts#L61-L65) inhibits the ability to use the validation utilities for non-packemon projects.

Previously, we would run all of the package.json files in a repository through the [`PackageValidate#validate`](https://github.com/milesj/packemon/blob/c40d20d06217d9cd6fc0e8fc67b52652a4707b25/packages/packemon/src/PackageValidator.ts#L38) method. Given that we only have some packages that are `packemon` enabled, this fails with the error:

```sh
Error: Invalid `packemon` configuration for <some-non-packemon-package>, must be an object or array of objects. 
``` 

Appreciate any workarounds here for constructing the required `Package` object so that we can continue to leverage the validation utilities would be helpful.

**Comment by milesj** [comment]
@j3tan 👋 

This should fix it: https://github.com/milesj/packemon/pull/178

**Comment by j3tan** [comment]
@milesj thanks!
