### ISSUE TITLE
Bug: `transform-react-jsx currently only accepts useBuiltIns or useSpread but not both`

### ISSUE THREAD

**Issue by j3tan** [milesj/packemon#181]
Hitting this issue while trying to upgrade to Packemon 3. Looks like it was part of the breaking changes in PR #160 but seems to impact packages using `react` JSX

```shell
Running `packemon build --addExports --no-addFiles --declaration --quiet --loadConfigs` in ./packages/some-package 

**ERROR** 
[BABEL] path/to/some/file.ts: transform-react-jsx currently only accepts useBuiltIns or useSpread but not both (While processing: "/src/web/node_modules/@babel/preset-react/lib/index.js$0")

STACK TRACE 
    at /src/web/node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:63:17
    ...
```

https://github.com/milesj/packemon/blob/c1cc7bae220017d9abf26b5b2ed3350fa3132e9b/packages/packemon/src/babel/config.ts#L145-L156

Related:
https://github.com/babel/babel/blob/34136c53f82976ee93eb72885beeacf9782d2e6a/packages/babel-plugin-transform-react-jsx/src/create-plugin.ts#L129-L136

https://github.com/babel/babel/blob/05deb6040523c0af4847c5c8f6d1589a0d8d3e89/packages/babel-helper-builder-react-jsx/src/index.ts#L266-L271

**Comment by milesj** [comment]
I wonder if this is a new warning, haven't seen it yet.

Regardless, turning off `useSpread`: https://github.com/milesj/packemon/pull/183
