### ISSUE TITLE
Bug: Assets are not being bundled properly when using esm bundle format

### ISSUE THREAD

**Issue by j3tan** [milesj/packemon#186]
Version: `packemon@3.x`

The `esm` format with bundling tries to copy an invalid asset into an `assets` folder.

```
Running `packemon build --addExports --no-addFiles --declaration --quiet --loadConfigs` in ./my-app 

ERROR
ENOENT: no such file or directory, copyfile '/path/to/my-app/app.css' -> '/path/to/my-app/assets/app-92722f3f.css'
```

My hunch is that the asset `import` path in the generated `index.js` file is incorrectly set. That means when we are doing the pass to generate hashed assets for files, it fails because the file path doesn't exist. It should point to the appropriate file (in `packemon@2.x` it looks like it uses `../assets/style-somehash.css`)

```
my-app/
├─ assets/
│  │  ├─ app-somehash.css (generated)
├─ src/
│  ├─ app/
│  │  ├─ app.css
│  │  ├─ index.ts
│  ├─ index.js (generated)
│  ├─ index.ts

```

```js
// src/index.js (generated file)
// Bundled with Packemon: https://packemon.dev
// Platform: browser, Support: stable, Format: esm

import 'app.css'; <=== This should probably be `../assets/app~somehash.css` or `./app/app.css`
function app() {
  console.log('app started');
}
export { app };
//# sourceMappingURL=index.js.map
```

Example repo: https://github.com/j3tan/packemon-asset-test

**Comment by j3tan** [comment]
Note: This one isn't super high priority, we temporarily switched to styled components for the one use case we had.

**Comment by j3tan** [comment]
Confirmed that `lib` without `bundle` still works properly.

**Comment by milesj** [comment]
@j3tan 

This is weird. So I added tests that cover a ton of scenarios, and you can see in the snapshots that the paths are correct (for all cases): https://github.com/milesj/packemon/pull/187/files#diff-b5d815bb70f76bd7e1fcb98f9cc01dcca0d38f1e0bd7ee77f6ff49470cffa870R292

Can you paste your config and I'll try to recreate an exact scenario.

This is also the plugin that handles the assets, if you're feeling adventurous in debugging it: https://github.com/milesj/packemon/blob/master/packages/packemon/src/rollup/plugins/copyAndRefAssets.ts

**Comment by j3tan** [comment]
Did you check out the example repo? 

https://github.com/j3tan/packemon-asset-test

I'm able to repro it there

**Comment by j3tan** [comment]
This is also highlighted if you have relative imports to the same file but from different directory levels

```
my-app/
├─ assets/
│  │  ├─ app-somehash.css (generated)
├─ src/
│  ├─ app/
│  │  ├─ nested/
│  │  │ ├─ index.ts <-- includes `../app.css`
│  │  ├─ app.css
│  │  ├─ index.ts <-- includes `./nested`
│  ├─ index.js (generated)
│  ├─ index.ts
```

This generated a bundled index.js file that looks like:
```js
// Bundled with Packemon: https://packemon.dev
// Platform: browser, Support: stable, Format: esm

import './app.css';
import '../app.css';
function nested() {
  console.log('nested');
}
function app() {
  console.log('app started');
  nested();
}
export { app };
//# sourceMappingURL=index.js.map

```

**Comment by milesj** [comment]
Was able to finally reproduce. Resolving to an absolute path seems to have resolved it: https://github.com/milesj/packemon/pull/187/files#diff-7141f8509be7eefed6ab87b3617e24a7d1ec58cb6330ba765a453821026491efR65
