### ISSUE TITLE
regeneratorRuntime is not defined in build output

### ISSUE THREAD

**Issue by kaleidawave** [milesj/packemon#19]
Attempting packemon for a project. Its building the project fast without errors. But the output contains references to `regeneratorRuntime` which is not in scope. Checking this [SO question](https://stackoverflow.com/a/64083314/10048799) it says the `@babel/plugin-transform-runtime` plugin should be used.. but I am not sure how to add that as packemon uses its internal babel configuration? Is there a way to extend it / add a plugin for it?

You can reproduce it by cloning the `fix-web-api-issues` branch [here](https://github.com/kaleidawave/prism/tree/fix-web-api-issues). Running `node lib/bin.js` should not throw.

Thanks 😁

**Comment by milesj** [comment]
That's odd since node platform enforces async/await always. Will take a look!

**Comment by milesj** [comment]
Ok so Packemon has this feature where if multiple platforms (web/node) all write to `lib`, then it "merges" them to be compatible. What's happening is that node platform is actually being compiled for the browser, which is resulting in the regenerator runtime coming through.

I'll have to think of a way to improve this further.

**Comment by milesj** [comment]
Also, you seem to be using generators, which I have not accounted for. That's also the other reason why it's pulled in.

I currently convert async/await to promises, but have no way to handle generators. Will dig into.

**Comment by kaleidawave** [comment]
Sounds complex! Thanks for taking a look. I can't remember using generators in the project, I may refactor those out to get it working.

**Comment by milesj** [comment]
No worries, adding support https://github.com/milesj/packemon/pull/22

**Comment by milesj** [comment]
@kaleidawave Released v0.10, can you give it a shot? You'll need to update your config to the following as there is more validation.

```
  "packemon": [
    {
      "inputs": {
        "index": "src/node.ts",
        "bin": "src/cli.ts"
      },
      "platform": "node"
    },
    {
      "inputs": {
        "web": "src/web.ts"
      },
      "platform": "browser",
      "support": "current"
    }
  ],
```

**Comment by kaleidawave** [comment]
Awesome, the node binary is working now! (and from v0.9 to v0.10 the compilation time has gone from 40s to 20s which is also great 👍)

Trying out `esm/web.js` now and having some issues:

First of all it does not like using the nodejs path module in the source: #24

Secondly seeing `regeneratorRuntime` in the web output without it being bundled / imported. I don't know a lot about `regeneratorRuntime` and why it is needed but at the moment it breaks doing `import x from "./esm/web.js"` as it can't read `mark` of undefined.

Once these hitches are fixed then it should be all working !!

**Comment by milesj** [comment]
I'll look into the node polyfills piece.

As for the runtime, you would need to add the `@babel/runtime` dep to your project, since it requires it. https://packemon.dev/docs/setup#transforming-generators

**Comment by milesj** [comment]
Going to close this since the initial issue is fixed.

**Comment by kaleidawave** [comment]
Awesome thank you very much! BUT before this is closed I'll double check the web build is working with `@babel/runtime`, will check this afternoon

**Comment by kaleidawave** [comment]
Okay think I have got path working for different contexts. In terms of the `regeneratorRuntime` thing I am still a little stuck:

I installed `regenerator-runtime` and added `import "regenerator-runtime/runtime.js";` to the top of the web entry point but am still getting this as the web output:

```js
// Generated with Packemon: https://packemon.dev
// Platform: browser, Support: current, Format: lib
'use strict';

var _this3 = this;

function _typeof(obj) { ... }

var _marked = /*#__PURE__*/regeneratorRuntime.mark(variableReferenceWalker),
    _marked2 = /*#__PURE__*/regeneratorRuntime.mark(filesInFolder);

...
```

But this does not work through importing straight in to a browser as `regeneratorRuntime` is not defined at all before that part. I don't know if the build stripped out and did not bundle the `import "regenerator-runtime/runtime.js";` part?? I am not really familiar with the babel ecosystem so am a little stuck ..?

**Comment by kaleidawave** [comment]
Hmm, okay I was [trying to reproduce the issue on replit](https://repl.it/@kaleidawave/PackemonGeneratorIssue) and its working as expected there lol. Will check again tomorrow, probably a issue with my packemon config

**Comment by milesj** [comment]
@kaleidawave Have you tried installing the `@babel/runtime` dep? The babel config should be transforming the generators to: 

```
var _regenerator = require("@babel/runtime/regenerator");

var _regenerator2 = _interopRequireDefault(_regenerator);

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj };
}

var _marked = [foo].map(_regenerator2.default.mark);
```

But to verify, this is for web platform only? Not for node yeah?

**Comment by milesj** [comment]
I tested your branch and I don't see the word `regenerator` in any of the built files. Did you resolve it?

**Comment by kaleidawave** [comment]
Yep, ending up refactoring out the generators rather than dealing with babel. Project is now compiling and packemon is working really well! Issue can be closed

**Comment by milesj** [comment]
Awesome, glad to hear!
