### ISSUE TITLE
Bug: browser condition block in exports is missing default

### ISSUE THREAD

**Issue by wespickett** [milesj/packemon#196]
version `3.x`

Builds in the Artifact are isolated per config:
https://github.com/milesj/packemon/blob/master/packages/packemon/src/Package.ts#L179-L202

So the findEntryPoint for lib here will always be null while an esm build is being processed: https://github.com/milesj/packemon/blob/master/packages/packemon/src/Artifact.ts#L324

So the default for browser (and maybe others?) needs to be added in at another point:

Possible fix:
[missingDefaults.patch](https://github.com/milesj/packemon/files/11375844/missingDefaults.patch)

**Comment by milesj** [comment]
@wespickett This is true for:

```
[
	{
		"format": "esm"
	},
	{
		"format": "lib"
	}
]
```

But not:

```
{
	"format": ["esm", "lib"]
}
```

But regardless, exports are deep-merged from all artifacts.

**Comment by wespickett** [comment]
@milesj 

https://github.com/wespickett/packemon-test1

Steps:
npm install
cd packages/example1
npm run build

Expected:
```
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "browser": {
        "types": "./esm/index.d.ts",
        "module": "./esm/index.js",
        "import": "./esm/index.js",
        "default": "./lib/index.js" <==== This is missing
      },
      "node": {
        "types": "./lib/index.d.ts",
        "default": "./lib/index.js"
      },
      "default": "./lib/index.js"
    }
  }
```

Actual:
```
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "browser": {
        "types": "./esm/index.d.ts",
        "module": "./esm/index.js",
        "import": "./esm/index.js"
      },
      "node": {
        "types": "./lib/index.d.ts",
        "default": "./lib/index.js"
      },
      "default": "./lib/index.js"
    }
  }
```

**Comment by milesj** [comment]
@wespickett That's unfortunately correct... `lib` is configured for `node`, and shouldn't appear under `browser`.

Are you actually having issues with this? `browser` is used by bundlers, nothing else, and would either use require/import anyways.

**Comment by milesj** [comment]
@wespickett v2 was actually wrong IMO.

Is browser really required in Jest? Browser is almost always ESM code, which isn't compatible with Jest.

**Comment by wespickett** [comment]
Removed the browser condition, and also changed the packemon configs to be ["esm", "lib"] for the browser platforms so the cjs code is generated for the defaults
