### ISSUE TITLE
Transpile without rolling up to index.js

### ISSUE THREAD

**Issue by ky-lee-cb** [milesj/packemon#204]
Hi Miles!

I have a project with the following file structure:
```
./src
├── index.js
└── theme
    ├── KBarAnimator.jsx
    └── KBarCellAccessory.jsx
```

`index.js` doesn't import any of the files but I need files to be rendered individually instead of rolled up to a single file. I looked at the docs but wasn't clear how I could do this.

Thanks!

**Comment by milesj** [comment]
@ky-lee-cb  Hey Ky 👋 

If you set `bundle` to false, it should transpile 1:1

https://packemon.dev/docs/config#bundle

**Comment by ky-lee-cb** [comment]
that was it! thank you!
