### ISSUE TITLE
clean command is not working

### ISSUE THREAD

**Issue by Karibash** [milesj/packemon#215]
When executing the clean command, artifacts are not cleaned up properly.
The reason for this bug is that the Package's artifacts property is an empty array when the clean command is executed.
To correct this bug, the [generateArtifacts function](https://github.com/milesj/packemon/blob/6b7154e37bad92e02fea7a4b2502d95159b516c0/packages/packemon/src/Package.ts#L172) should be executed before executing the [clean function](https://github.com/milesj/packemon/blob/6b7154e37bad92e02fea7a4b2502d95159b516c0/packages/packemon/src/commands/Clean.ts#L9) of Package to generate the artifacts in advance.

**Comment by milesj** [comment]
Thanks fixed.
