### ISSUE TITLE
"helpers" feature not removing babelHelpers

### ISSUE THREAD

**Issue by lachiet** [milesj/packemon#219]
Hey @milesj - following on from the discussion on https://github.com/milesj/packemon/issues/207

- I've tried all the options for the `features.helpers` field and I'm still seeing the babelHelpers bundled inline.
- I tested invalid values to make sure the config was picking this up, but it wouldn't start without one of the 4 valid options.

I noticed you mentioned in the previous issue:
> But I can't seem to get the snapshots to reflect the helper changes, and I can't figure out why...

From looking at the snapshots in your [PR](https://github.com/milesj/packemon/pull/211) to implement the helper option, I would expect [Scenario 2](https://github.com/milesj/packemon/pull/211/files#diff-b5d815bb70f76bd7e1fcb98f9cc01dcca0d38f1e0bd7ee77f6ff49470cffa870R44) not to have the babel helpers above the example function because it's set to be external [here](https://github.com/milesj/packemon/pull/211/files#diff-8bc0fa96283ae5eba60b34fb65f5d008521fe2ac7816fdf256a5f42da54556d0R252)? This is the same output I'm seeing when setting the config locally and build too:

![image](https://github.com/milesj/packemon/assets/30222060/18db9754-0a2c-4ea5-93fa-7f022298f6f8)

**Comment by milesj** [comment]
After spending hours debugging this, I think I figured it out here: https://github.com/milesj/packemon/pull/220

The issue was I was passing the `@babel/plugin-transform-runtime` plugin to _babel input_ instead of _babel output_.

Like... come on.

**Comment by milesj** [comment]
Ok can you try 3.2.2
