### ISSUE TITLE
[Docs] Meaning of directory name colors of `npx packemon files`

### ISSUE THREAD

**Issue by BinToss** [milesj/packemon#221]
Not yet documented at https://packemon.dev/docs/files
- Red is non-code?
- Green is build output?
- Magenta is source?
![image](https://github.com/milesj/packemon/assets/7243190/ee0b6e00-9729-4374-a7cf-05085c8e0585)

**Comment by milesj** [comment]
It's the configured platforms/formats:

purple = source code
green (node) = cjs/mjs
yellow (browser) = lib/esm/umd
teal = dts
red = other
