### ISSUE TITLE
Web builds should polyfill node libraries 

### ISSUE THREAD

**Issue by kaleidawave** [milesj/packemon#24]
Currently building a nodejs project that the path module:

The web output (`esm/web.js`) currently has this import:

```js
...
// Generated with Packemon: https://packemon.dev
// Platform: browser, Support: current, Format: esm
import { relative, dirname, join, posix, resolve, basename, isAbsolute } from 'path';
...
```

This first of all breaks parsing as browsers do not like non relative import paths (`Uncaught TypeError: Failed to resolve module specifier "path". Relative references must start with either "/", "./", or "../"`)

It also is not a valid import as the `path` module library is not available in browsers. It would great if it could "polyfill" / "shim" the `path` module similar to [webpack](https://webpack.js.org/configuration/node/) for web builds

**Comment by milesj** [comment]
@kaleidawave Before I dive into this, are you using the ESM files directly in the browser, or through a bundler?

**Comment by kaleidawave** [comment]
@milesj Directly in the browser. Ideally `packemon` will be used as the only build tool for this project. 

[`path-browserify`](https://www.npmjs.com/package/path-browserify) is the node path mirror package that I am looking at `import path from "path"` being bundled/swapped in for under browser builds. I think the *path* is the only nodejs lib that needs polyfilling as others are not relevant for browser environment.  👍

**Comment by milesj** [comment]
This would solve the problem and support more than `path`. However, need to wait for an official release. https://github.com/snowpackjs/rollup-plugin-polyfill-node

**Comment by kaleidawave** [comment]
Awesome that's fine. I will replace the path lib with the `path-browserify` module for the meantime

**Comment by milesj** [comment]
@kaleidawave This should work in v11. Not sure of the quality of the polyfills though.

Also improved generator support.

**Comment by kaleidawave** [comment]
Thank you for adding this!! Will try it out tomorrow 👍

**Comment by kaleidawave** [comment]
Yep just tried it out. [The node and web builds are working perfectly](https://repl.it/@kaleidawave/PackemonPathPolyfillTest#.replit).  😁. Will try it out in the original project

**Comment by milesj** [comment]
Awesome, glad to hear!
