### ISSUE TITLE
[4.0] Packemon ignores tsconfig `outDir`

### ISSUE THREAD

**Issue by svallory** [milesj/packemon#245]
Since there's only one format in v4, I kinda expected it to follow tsconfig `outDir`. It's fine if it doesn't, but how do I configure packemon's output to `lib` instead of `mjs`?

**Comment by milesj** [comment]
@svallory Not sure I follow, all the formats still exist in v4. If you want `lib`, set the `format` to lib, and then use `tsconfig.lib.json`.

**Comment by svallory** [comment]
I don't want the `lib` format. I want to output `esm` (or `mjs`) to the `lib/` folder

**Comment by svallory** [comment]
On a side note, I understand packemon does not follow the `tsconfig` (since we need `--declaration` to output `.d.ts` regardless of what is set in the `tsconfig`). So it would be nice to have some documentation regarding packemon's build process and how to control it.

Right now, it's hard to understand what in the `tsconfig` does and what does not affect the build. And for the things that can't be configured there, where can I configure it?

**Comment by milesj** [comment]
Well, you can't control the output outside of setting the format. The format = the directory name, and that's not going to change. It's very tightly coupled to how rolldown is configured and works.

The only thing tsconfig is used for is generating declarations. I don't read the config for anything really.

**Comment by svallory** [comment]
>  I don't read the config for anything really.

So there's no way to control `allowImplicitAny`, `strict`, etc? Wait... actually, `resolveJsonModules` does have an effect. I had to change it to be able to compile the project. How is that so?

**Comment by svallory** [comment]
Oh, and there's one more thing... if I set `outDir` to a folder other than the packemon's expected folder, both folder's get generated with all files.

Can I disable packemon's output and use `tsc` while doing all the rest `pack` does?

**Comment by milesj** [comment]
@svallory Not really. Rollup writes to the format designated folder. 

Typescript is weird, since we just call `tsc`. It's up to you to configure it correctly. Primarily to output declarations to the correct path (the format folder).

**Comment by svallory** [comment]
> @svallory Not really. Rollup writes to the format designated folder.
> 
> Typescript is weird, since we just call `tsc`. It's up to you to configure it correctly. Primarily to output declarations to the correct path (the format folder).

Ok, thanks! I'm kinda picky and not being able to control compilation makes things very complicated to me. I'm used to tsc so, for me, usually it's the tool taking that control from me that gets me into trouble.

But packemon adds a lot and I don't want to give that up so I guess I'll let it build then delete the build and build again with tsc. I just did that as a test and got errors I wasn't getting from `packemon pack`.

tbh, typescript IS weird, but it's a weirdness I know. Using anything other than `tsc` to build typescript is inviting more weirdness. For example, most "fast" ts compilers drop type checking which doesn't make any sense to me. Either I add an extra typecheck step using `tsc` (which is slower than just building with tsc) or there's no point in using TS

Anyway, I'm closing the issue since this is not a bug. And really, thank you for the help and for packemon, it is still really great!

**Comment by milesj** [comment]
@svallory Curious, if you delete the rollup format build, and use `tsc` instead, what features of `pack` do you want exactly?

**Comment by svallory** [comment]
> @svallory Curious, if you delete the rollup format build, and use `tsc` instead, what features of `pack` do you want exactly?

Lots! Automatic engines, files, and exports updates. Package validation has saved me a few times by checking if types, bin, and main are pointing to the right place, all the automatic configuration update, adding new projects via the scaffold...

from all the features packemon has, the build is the less interesting to me

**Comment by svallory** [comment]
@milesj well, to be fair, that's only true now! When this mess of `cjs` and `mjs` started, packemon would have been a life saver!

I had a lot of headaches until I found a setup that allowed me to work as I always did and compile to everything from the same source. And that's why I'm so reluctant to give away control over how the project is built

**Comment by svallory** [comment]
And there's one more thing... If I can't control the build via tsconfig, how can I configure the build and reference of pure typescript libraries? By TS libs I mean ts projects that are not node packages (at least not ones that will be consumed as packages)

I tend to do that a lot to enforce boundaries and optimize tsc build via project references. That's something that's rarely supported in monorepo and node build tools. (I'm KINDA bringing that to moon via templates)
