### ISSUE TITLE
Scan package lock file (or deps?) for highest minimum engine requirements for --addEngines

### ISSUE THREAD

**Issue by BinToss** [milesj/packemon#255]
At the time of writing, Packemon 4.0.1 will set the package's Node engine version to `>=18.12.0`, but one of my dependencies, semantic-release, requires at least NodeJS 20.8.1 and will not run on earlier versions.

I now periodically search through package-lock.json for engine requirement changes.

**Comment by milesj** [comment]
@BinToss This won't change, as the engine version is tied to certain features that are necessary for functionality in packemon: https://github.com/milesj/packemon/blob/master/packages/packemon/src/constants.ts#L80

I'd suggest not using `--addEngines` if it causes issues.
