### ISSUE TITLE
Handling tsconfig paths

### ISSUE THREAD

**Issue by kyhyco** [milesj/packemon#264]
Hello there old friend!

I am building a typescript package using packemon. I added a new path in the tsconfig. Something like:
```json
{
  "compilerOptions": {
    "baseUrl": "./"
    "paths": [
        ":package-name/*" : "./src/*"
    ] 
  }
}
```

Typescript itself picks this up just fine but packemon does not. Getting something like:
```bash
[@org/name:name] ":package-name/folder" is imported by "src/Component.tsx", but could not be resolved – treating it as an external dependency. ...
```

The desire effect is for the bundle to convert `:package-name/folder` to relative import in the generated esm package.

Looked around the source code and I assume packemon can't do this yet, right?

**Comment by milesj** [comment]
Yeah packemon doesn't do this by default. I personally don't like using path aliases within packages.

You can probably work around this be enabling the babel tsconfig plugins: https://packemon.dev/docs/advanced#customizing-babel-swc-and-rollup

**Comment by kyhyco** [comment]
The following works:

**tsconfig.json**
```json
{
  "compilerOptions": {
    // ...
    "baseUrl": ".",
    "paths": {
      ":ock/*": ["src/*"]
    }
  }
}
```

**packemon.config.ts**
```typescript
import type { ConfigFile } from 'packemon';

const config: ConfigFile = {
  babelInput(config) {
    const moduleResolverPath = require.resolve('babel-plugin-module-resolver');
    config.plugins?.push([
      moduleResolverPath,
      {
        root: './',
        alias: {
          ':ock': './src',
        },
      },
    ]);
  },
};

export default config;
```

Thank you so much Miles!

**Comment by milesj** [comment]
Nice, easy enough fix!
