### ISSUE TITLE
--project flag with project references

### ISSUE THREAD

**Issue by branclar** [milesj/packemon#58]
Howdy!

I ran across an issue with the `--project` flag on being attached to my pack script in a project using project references. 

Looks like you've already addressed that issue with this [commit](https://github.com/milesj/packemon/commit/c2e7cd7fde789457aba358279484380ca93befa1).

What is your typical cadence for releasing hotfixes such as these?

**Comment by milesj** [comment]
Yeah, I'm gonna try and land this in the next day or two and then release, as it fixes some other issues: https://github.com/milesj/packemon/pull/59

**Comment by milesj** [comment]
@branclar Published a new release.
