### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by milesj** [milesj/packemon#61]
After the last few PRs, Packemon feels rather stable and feature complete enough for a v1. I will leave this issue open for a while to test a bit more and receive any feedback.

With that being said, I plan on making the following changes for the v1 release since they are breaking:

- Drop Node v10 support since its EOL: https://nodejs.org/en/about/releases/
- Update all the support versions.

### Controversial? Force modules by default?

Now that Node v12.18+ supports ES modules, we're dropping Node v10, and everyone pretty much writes their code nowadays with import/export, perhaps we force ES as the default? This would make `mjs` the default for node and `esm` the default for browser. `lib` would still exist, just opt-in.

**Comment by milesj** [comment]
@branclar @jon301 @kaleidawave Since yall were early adopters, is there anything you would like to see in v1? Also thoughts on ESM first?

**Comment by kaleidawave** [comment]
Yah dropping node10 is fine. ESM all the way!

**Comment by milesj** [comment]
Published an alpha release, if y'all would like to test it. https://github.com/milesj/packemon/releases/tag/v1.0.0-alpha.0
